---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
    author: intelliqit
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: a
...
          
