---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    author: intelliqit
type: Opaque
stringData:
  password: aW50ZWxsaXFpdAo=
  username: bXl1c2VyCg== 
  dbname: bXlkYgo= 
...
